### model
model_name_or_path: unsloth/Qwen3-4B-Instruct-2507-unsloth-bnb-4bit
adapter_name_or_path: saves/stage1_lora   # Reprend là où Stage 1 s'est arrêté

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_target: all

### dataset
dataset_dir: data_filtered
dataset: stage2_filtered
template: qwen3
cutoff_len: 1024
max_samples: 90
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: saves/stage2_lora
logging_steps: 5
save_steps: 45
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 45
